name: smarttownconnect
description: A responsive Flutter app for modern township community management.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  provider: ^6.0.5
  fluttertoast: ^8.2.4

  # HTTP & Backend
  http: ^1.2.0
  shared_preferences: ^2.2.2

  # Firebase (optional, if you're using Firebase Auth, Firestore, FCM)
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  firebase_messaging: ^14.7.0

  # Location & Maps (Optional if you need)
  location: ^5.0.3
  geolocator: ^11.0.0

  # Media
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1

  # Misc
  intl: ^0.19.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

